"""add newsroom models.

Revision ID: 76da1d3f342c
Revises: 25a32b4bd959
Create Date: 2026-04-28 20:19:02.853603
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76da1d3f342c"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "25a32b4bd959"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_config",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_agent_config_key"), "agent_config", ["key"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_ignored", sa.Boolean(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=True)
    op.create_table(
        "entity_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entity_types_name"), "entity_types", ["name"], unique=True)
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subtype", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("health_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=False)
    op.create_table(
        "entity_sources",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id", "source_id"),
    )
    op.create_table(
        "news_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_snippet", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_content", sa.Text(), nullable=True),
        sa.Column("title_es", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content_es", sa.Text(), nullable=True),
        sa.Column("entities_extracted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_items_source_id"), "news_items", ["source_id"], unique=False)
    op.create_index(op.f("ix_news_items_title"), "news_items", ["title"], unique=False)
    op.create_index(op.f("ix_news_items_url"), "news_items", ["url"], unique=True)
    op.create_table(
        "news_entities",
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["news_id"],
            ["news_items.id"],
        ),
        sa.PrimaryKeyConstraint("news_id", "entity_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("news_entities")
    op.drop_index(op.f("ix_news_items_url"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_title"), table_name="news_items")
    op.drop_index(op.f("ix_news_items_source_id"), table_name="news_items")
    op.drop_table("news_items")
    op.drop_table("entity_sources")
    op.drop_index(op.f("ix_sources_name"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_entity_types_name"), table_name="entity_types")
    op.drop_table("entity_types")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_agent_config_key"), table_name="agent_config")
    op.drop_table("agent_config")
    # ### end Alembic commands ###
