"""Refactor sources.

Revision ID: 8d18056dcfbc # pragma: allowlist secret
Revises: fa880fbb50a1
Create Date: 2026-04-30 12:59:11.683204
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d18056dcfbc"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "fa880fbb50a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("sources", sa.Column("last_error", sa.Text(), nullable=True))
    op.create_index(op.f("ix_sources_category"), "sources", ["category"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_category"), table_name="sources")
    op.drop_column("sources", "last_error")
    op.drop_column("sources", "category")
    # ### end Alembic commands ###
