"""Implementacion de perfil de fuente profesional.

Revision ID: da7a05316df1 # pragma: allowlist secret
Revises: 76da1d3f342c
Create Date: 2026-04-29 18:32:00.993834
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da7a05316df1"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "76da1d3f342c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Crear el tipo ENUM explícitamente en PostgreSQL antes de usarlo
    sourcehealth = postgresql.ENUM("HEALTHY", "DEGRADED", "OFFLINE", "BANNED", name="sourcehealth")
    sourcehealth.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sources", sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("sources", sa.Column("last_fetch_attempt", sa.DateTime(), nullable=True))
    op.add_column("sources", sa.Column("last_successful_fetch", sa.DateTime(), nullable=True))
    op.add_column("sources", sa.Column("consecutive_errors", sa.Integer(), nullable=False))
    op.add_column("sources", sa.Column("tier", sa.Integer(), nullable=False))
    op.add_column("sources", sa.Column("trust_score", sa.Float(), nullable=False))
    op.add_column("sources", sa.Column("fetch_frequency_minutes", sa.Integer(), nullable=False))
    op.add_column("sources", sa.Column("scraping_strategy", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("sources", sa.Column("etag", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("sources", sa.Column("last_modified_header", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column("sources", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("sources", "type", existing_type=sa.VARCHAR(), nullable=False)
    # Convertir el texto viejo "OK" al texto nuevo "HEALTHY" antes de castear a ENUM
    op.execute("UPDATE sources SET health_status = 'HEALTHY' WHERE health_status = 'OK'")

    op.alter_column(
        "sources",
        "health_status",
        existing_type=sa.VARCHAR(),
        type_=sa.Enum("HEALTHY", "DEGRADED", "OFFLINE", "BANNED", name="sourcehealth"),
        existing_nullable=False,
        postgresql_using="health_status::sourcehealth",
    )
    op.create_index(op.f("ix_sources_url"), "sources", ["url"], unique=True)
    op.drop_column("sources", "config")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sources", sa.Column("config", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_sources_url"), table_name="sources")
    op.alter_column(
        "sources",
        "health_status",
        existing_type=sa.Enum("HEALTHY", "DEGRADED", "OFFLINE", "BANNED", name="sourcehealth"),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column("sources", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("sources", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("sources", "last_modified_header")
    op.drop_column("sources", "etag")
    op.drop_column("sources", "scraping_strategy")
    op.drop_column("sources", "fetch_frequency_minutes")
    op.drop_column("sources", "trust_score")
    op.drop_column("sources", "tier")
    op.drop_column("sources", "consecutive_errors")
    op.drop_column("sources", "last_successful_fetch")
    op.drop_column("sources", "last_fetch_attempt")
    op.drop_column("sources", "url")
    # ### end Alembic commands ###

    # Eliminar el tipo ENUM explícitamente en PostgreSQL
    sourcehealth = postgresql.ENUM("HEALTHY", "DEGRADED", "OFFLINE", "BANNED", name="sourcehealth")
    sourcehealth.drop(op.get_bind(), checkfirst=True)
