"""Add entity linking fields to Entity model.

Revision ID: df7ee443545e
Revises: bd2818c8b267
Create Date: 2026-05-02 10:21:57.546211
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df7ee443545e"
down_revision: Union[str, Sequence[str], None] = "bd2818c8b267"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("entities", sa.Column("wikidata_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("entities", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("entities", sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("entities", sa.Column("wikipedia_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_entities_wikidata_id"), "entities", ["wikidata_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entities_wikidata_id"), table_name="entities")
    op.drop_column("entities", "wikipedia_url")
    op.drop_column("entities", "image_url")
    op.drop_column("entities", "description")
    op.drop_column("entities", "wikidata_id")
    # ### end Alembic commands ###
