"""Heredar trust_score y tier en NewsItem.

Revision ID: fa880fbb50a1
Revises: da7a05316df1
Create Date: 2026-04-29 18:50:46.602635
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa880fbb50a1"
down_revision: Union[str, Sequence[str], None] = "da7a05316df1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_items", sa.Column("trust_score", sa.Float(), nullable=False))
    op.add_column("news_items", sa.Column("tier", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_items", "tier")
    op.drop_column("news_items", "trust_score")
    # ### end Alembic commands ###
